//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlyDonHang_DoAn_hqtcsdl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
        public Nullable<System.DateTime> BirthDayKH { get; set; }
        public string GioiTinhKH { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
