//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlyDonHang_DoAn_hqtcsdl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Order_Id { get; set; }
        public string OrderNo { get; set; }
        public string Status { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalAmount { get; set; }
        public string ShippingAddress { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool IsCancel { get; set; }
        public int MaKH { get; set; }
        public Nullable<int> Payment_Id { get; set; }
        public Nullable<int> Coupon_Id { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelledBy { get; set; }
        public string CancelReason { get; set; }
        public string InternalNote { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
