//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlyDonHang_DoAn_hqtcsdl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Product_Image_Mapping = new HashSet<Product_Image_Mapping>();
            this.Product_Image_Mapping1 = new HashSet<Product_Image_Mapping>();
        }
    
        public int Product_Id { get; set; }
        public string ProductName { get; set; }
        public string ProductSlug { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public int Quantity { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> SoldCount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Category_Id { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public Nullable<int> DefaultImage_Id { get; set; }
        public Nullable<int> Size_Id { get; set; }
        public Nullable<int> Color_Id { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Product_Image_Mapping> Product_Image_Mapping { get; set; }
        public virtual ProductImage ProductImage { get; set; }
        public virtual ProductImage ProductImage1 { get; set; }
        public virtual ICollection<Product_Image_Mapping> Product_Image_Mapping1 { get; set; }
    }
}
