//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlyDonHang_DoAn_hqtcsdl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCounter
    {
        public int CounterID { get; set; }
        public Nullable<int> TotalRequests { get; set; }
    }
}
