//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlyDonHang_DoAn_hqtcsdl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public ProductImage()
        {
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
            this.Product_Image_Mapping = new HashSet<Product_Image_Mapping>();
            this.Product_Image_Mapping1 = new HashSet<Product_Image_Mapping>();
        }
    
        public int Image_Id { get; set; }
        public string ImageUrl { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<Product_Image_Mapping> Product_Image_Mapping { get; set; }
        public virtual ICollection<Product_Image_Mapping> Product_Image_Mapping1 { get; set; }
    }
}
